### ISSUE TITLE
LeddarTech Vu8

### ISSUE THREAD

**Issue by jckchow** [mcgill-robotics/ros-leddar#1]
Hello,

I followed the instructions and was able to compile the code without any issues. However, when I run $ roslaunch leddar leddar.launch serial:=######, I get the error message "Failed to connect to <My Serial Number> with code: -1". I am wondering if anyone has experience with using this ROS package with the new Vu8? Thanks.

**Comment by anassinator** [comment]
Hello,

Unfortunately, we don't have a Vu8 to test with, but it's most definitely due to the Leddar SDK in use being out of date. It seems we need v3.2.0.208 to support the Vu8 and that was just released 5 days ago. You could try updating what's in `lib/` and `include/` with what's packaged in the latest release from their website: support.leddartech.com (although I can't seem to find a link to that latest driver update for linux yet).

FYI, we are still packaging v2.10.x simply due to not having needed to update ourselves yet, so I'm not sure what issues you'll run into as it's a major version bump. Regardless, let me know if you run into any issues and I'll try to help out.

**Comment by nmanivan** [comment]
Hello, 

I also followed the instructions like jckchow with no problems until I used "catkin_make" and I got an error message "Linking CXX executable /home/narayan/catkin_ws/devel/lib/leddar/leddar
/usr/bin/ld: cannot find -lLeddarTech
/usr/bin/ld: cannot find -lLeddar
/usr/bin/ld: cannot find -lLeddarC
collect2: error: ld returned 1 exit status
make[2]: *** [/home/narayan/catkin_ws/devel/lib/leddar/leddar] Error 1
make[1]: *** [leddar/CMakeFiles/leddar.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j8 -l8" failed
"
I am also using the LeddarVu8 and am wondering if anyone has experience in using this package with the Vu8.  Any help would be appreciated. Thanks

**Comment by daizr** [comment]
@jckchow @nmanivan if you can use it over [CAN](https://en.wikipedia.org/wiki/CAN_bus) bus we're using [this one](https://github.com/dispatch-ai/ros-leddar-vu8)

**Comment by anassinator** [comment]
This should be fixed now

**Comment by anassinator** [comment]
This package should theoretically work with the M16, but was never explicitly tested by us. You should just follow the instructions in the README.

**Comment by kolohe113** [comment]
I am trying to run the VU8 on Ros using Ubuntu 16.04LTS. Do we have to use a PCAN to USB? How about a USB to mini usb connection?

**Comment by anassinator** [comment]
Sorry, I don't know. We don't own a Vu8 ourselves. Whatever works with the examples they provide with their SDK should work with this as well.

**Comment by veervishu99** [comment]
Hey have you figure out this problem, actually, my problem is same that's why I am asking you about this
